[window]
dynamic_padding = true
padding.x = 5
padding.y = 5
opacity = 1
decorations = "none"

[env]
TERM = "xterm-256color"

[scrolling]
history = 10000
multiplier = 3

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#282c34"
foreground = "#abb2bf"

[colors.cursor]
text = "#282c34"
cursor = "#528bff"

[colors.normal]
black   = "#282c34"
red     = "#e06c75"
green   = "#98c379"
yellow  = "#e5c07b"
blue    = "#61afef"
magenta = "#c678dd"
cyan    = "#56b6c2"
white   = "#dcdfe4"

[colors.bright]
black   = "#5c6370"
red     = "#e06c75"
green   = "#98c379"
yellow  = "#e5c07b"
blue    = "#61afef"
magenta = "#c678dd"
cyan    = "#56b6c2"
white   = "#ffffff"

[font]
size = 13
offset.x = 0
offset.y = 0

glyph_offset.x = 0
glyph_offset.y = 0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "SemiBold"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "ExtraBold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "SemiBold Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "ExtraBold Italic"

[cursor]
style = { shape = "Beam", blinking = "On" }
blink_interval = 700
unfocused_hollow = true
thickness = 0.15

